python get_cams.py --name generate_cams \
                   --data_dir /data4/PE_stanford/Stanford_data \
                   --ckpt_path /data4/PE_stanford/ckpts/penet_best.pth.tar \
                   --cam_dir cams \
                   --num_cams 10 \
                   --dataset pe \
                   --resize_shape=208,208 \
                   --crop_shape=192,192 \
                   --batch_size=1 \
                   --num_slices=24 \
                   --agg_method=max \
                   --gpu_ids=1
